-- Custom SQL migration file, put your code below! --
INSERT INTO "writers" ("uuid", "name", "created_at", "updated_at") VALUES
(gen_random_uuid(), 'Taylor Swift', now(), now()),
(gen_random_uuid(), 'Aaron Dessner', now(), now()),
(gen_random_uuid(), 'Max Martin', now(), now()),
(gen_random_uuid(), 'Shellback', now(), now()),
(gen_random_uuid(), 'Louis Bell', now(), now()),
(gen_random_uuid(), 'Frank Dukes', now(), now()),
(gen_random_uuid(), 'Liz Rose', now(), now()),
(gen_random_uuid(), 'Tom Petty', now(), now()),
(gen_random_uuid(), 'Jack Antonoff', now(), now()),
(gen_random_uuid(), 'Patrick Monahan', now(), now()),
(gen_random_uuid(), 'Kendrick Lamar', now(), now()),
(gen_random_uuid(), 'Andrew Lloyd Webber', now(), now()),
(gen_random_uuid(), 'Donna Weiss', now(), now()),
(gen_random_uuid(), 'Jackie DeShannon', now(), now()),
(gen_random_uuid(), 'William Bowery', now(), now()),
(gen_random_uuid(), 'Stephony Smith', now(), now()),
(gen_random_uuid(), 'Bobby Ray Simmons, Jr.', now(), now()),
(gen_random_uuid(), 'Ammar Malik', now(), now()),
(gen_random_uuid(), 'Lukasz Gottwald', now(), now()),
(gen_random_uuid(), 'Henry Walter', now(), now()),
(gen_random_uuid(), 'Colbie Caillat', now(), now()),
(gen_random_uuid(), 'Nathan Chapman', now(), now()),
(gen_random_uuid(), 'Imogen Heap', now(), now()),
(gen_random_uuid(), 'Dan Wilson', now(), now()),
(gen_random_uuid(), 'Robert Ellis Orrall', now(), now()),
(gen_random_uuid(), 'St. Vincent', now(), now()),
(gen_random_uuid(), 'Oscar Holter', now(), now()),
(gen_random_uuid(), 'Charlie Colin', now(), now()),
(gen_random_uuid(), 'Rob Hotchkiss', now(), now()),
(gen_random_uuid(), 'Jimmy Stafford', now(), now()),
(gen_random_uuid(), 'Pat Monahan', now(), now()),
(gen_random_uuid(), 'Scott Underwood', now(), now()),
(gen_random_uuid(), 'Ed Sheeran', now(), now()),
(gen_random_uuid(), 'Nayvadius Wilburn', now(), now()),
(gen_random_uuid(), 'Justin Vernon', now(), now()),
(gen_random_uuid(), 'Hillary Lindsey', now(), now()),
(gen_random_uuid(), 'John Mayer', now(), now()),
(gen_random_uuid(), 'Mark Irwin', now(), now()),
(gen_random_uuid(), 'Josh Kear', now(), now()),
(gen_random_uuid(), 'Brad Warren', now(), now()),
(gen_random_uuid(), 'Brett Warren', now(), now()),
(gen_random_uuid(), 'Blu Sanders', now(), now()),
(gen_random_uuid(), 'Sam Dew', now(), now()),
(gen_random_uuid(), 'Ryan Tedder', now(), now()),
(gen_random_uuid(), 'Freddie Perren', now(), now()),
(gen_random_uuid(), 'Deke Richards', now(), now()),
(gen_random_uuid(), 'Berry Gordy, Jr.', now(), now()),
(gen_random_uuid(), 'Alphonso Mizell', now(), now()),
(gen_random_uuid(), 'Martin Johnson', now(), now()),
(gen_random_uuid(), 'Angelo Petraglia', now(), now()),
(gen_random_uuid(), 'George Michael', now(), now()),
(gen_random_uuid(), 'Gary Lightbody', now(), now()),
(gen_random_uuid(), 'Jacknife Lee', now(), now()),
(gen_random_uuid(), 'Paula Fernandes', now(), now()),
(gen_random_uuid(), 'Cautious Clay', now(), now()),
(gen_random_uuid(), 'Sounwave', now(), now()),
(gen_random_uuid(), 'Fred Fairbrass', now(), now()),
(gen_random_uuid(), 'Richard Fairbrass', now(), now()),
(gen_random_uuid(), 'Rob Manzoli', now(), now()),
(gen_random_uuid(), 'Shawn Mendes', now(), now()),
(gen_random_uuid(), 'Scott Harris', now(), now()),
(gen_random_uuid(), 'T. S. Eliot', now(), now()),
(gen_random_uuid(), 'Joel Little', now(), now()),
(gen_random_uuid(), 'Brian Maher', now(), now()),
(gen_random_uuid(), 'Brendon Urie', now(), now()),
(gen_random_uuid(), 'Brett James', now(), now()),
(gen_random_uuid(), 'Troy Verges', now(), now()),
(gen_random_uuid(), 'Ali Payami', now(), now()),
(gen_random_uuid(), 'Maya Thompson', now(), now()),
(gen_random_uuid(), 'Joy Williams', now(), now()),
(gen_random_uuid(), 'John Paul White', now(), now()),
(gen_random_uuid(), 'T-Bone Burnett', now(), now()),
(gen_random_uuid(), 'Joan Javits', now(), now()),
(gen_random_uuid(), 'Philip Springer', now(), now()),
(gen_random_uuid(), 'Tony Springer', now(), now()),
(gen_random_uuid(), 'Maurice White', now(), now()),
(gen_random_uuid(), 'Al McKay', now(), now()),
(gen_random_uuid(), 'Allee Willis', now(), now()),
(gen_random_uuid(), 'Josef Mohr', now(), now()),
(gen_random_uuid(), 'Franz Xaver Gruber', now(), now()),
(gen_random_uuid(), 'Oscar Görres', now(), now()),
(gen_random_uuid(), 'Christopher Tricky Stewart', now(), now()),
(gen_random_uuid(), 'Terius Dream Nash', now(), now()),
(gen_random_uuid(), 'Thaddis Harrell', now(), now()),
(gen_random_uuid(), 'Shawn Carter', now(), now()),
(gen_random_uuid(), 'Cary Barlowe', now(), now()),
(gen_random_uuid(), 'Nathan Barlowe', now(), now()),
(gen_random_uuid(), 'Tommy Lee James', now(), now()),
(gen_random_uuid(), 'John Rich', now(), now()),
(gen_random_uuid(), 'Irving Berlin', now(), now())
;
