-- Custom SQL migration file, put your code below! --
INSERT INTO "albums" ("uuid", "name", "created_at", "updated_at") VALUES
(gen_random_uuid(), '1989', now(), now()),
(gen_random_uuid(), '1989 (Deluxe edition)', now(), now()),
(gen_random_uuid(), 'AT&T Team USA Soundtrack and Fearless', now(), now()),
(gen_random_uuid(), 'Battle Studies', now(), now()),
(gen_random_uuid(), 'Beautiful Eyes', now(), now()),
(gen_random_uuid(), 'Bigger', now(), now()),
(gen_random_uuid(), 'Cats: Highlights from the Motion Picture Soundtrack', now(), now()),
(gen_random_uuid(), 'Fearless', now(), now()),
(gen_random_uuid(), 'Fearless (Platinum edition)', now(), now()),
(gen_random_uuid(), 'Fearless (Platinum edition) and Valentine''s Day: Soundtrack', now(), now()),
(gen_random_uuid(), 'Fifty Shades Darker: Original Motion Picture Soundtrack', now(), now()),
(gen_random_uuid(), 'Folklore', now(), now()),
(gen_random_uuid(), 'Folklore (Physical Edition)', now(), now()),
(gen_random_uuid(), 'Hannah Montana: The Movie', now(), now()),
(gen_random_uuid(), 'Hope for Haiti Now', now(), now()),
(gen_random_uuid(), 'iTunes Live from SoHo', now(), now()),
(gen_random_uuid(), 'Live in No Shoes Nation', now(), now()),
(gen_random_uuid(), 'Love Drunk', now(), now()),
(gen_random_uuid(), 'Lover', now(), now()),
(gen_random_uuid(), 'One Chance Soundtrack', now(), now()),
(gen_random_uuid(), 'Red', now(), now()),
(gen_random_uuid(), 'Red (Deluxe edition)', now(), now()),
(gen_random_uuid(), 'Reputation', now(), now()),
(gen_random_uuid(), 'Rhapsody Originals', now(), now()),
(gen_random_uuid(), 'Sounds of the Season', now(), now()),
(gen_random_uuid(), 'Speak Now', now(), now()),
(gen_random_uuid(), 'Speak Now (Deluxe edition)', now(), now()),
(gen_random_uuid(), 'Speak Now World Tour – Live', now(), now()),
(gen_random_uuid(), 'Spotify Singles', now(), now()),
(gen_random_uuid(), 'Strange Clouds', now(), now()),
(gen_random_uuid(), 'Taylor Swift', now(), now()),
(gen_random_uuid(), 'Taylor Swift (Deluxe edition)', now(), now()),
(gen_random_uuid(), 'The Hunger Games', now(), now()),
(gen_random_uuid(), 'Two Lanes of Freedom', now(), now()),
(gen_random_uuid(), 'Valentine''s Day', now(), now())
;
